-- 
-- 
-- 
-- ------TABLE DATA FOR IMPORT `bciccom_db`.`3cx_users`
-- 
-- 
-- 
INSERT INTO `bciccom_db`.`3cx_users`  VALUES ('1' , 'Payal' , 'Payal' , 'Payal(102)' , '2017-08-16 21:03:52' ) ;
 
INSERT INTO `bciccom_db`.`3cx_users`  VALUES ('2' , 'Michael' , 'Michael' , 'Michael(101)
' , '2017-08-16 21:03:57' ) ;
 
INSERT INTO `bciccom_db`.`3cx_users`  VALUES ('3' , 'Dhruv Bhati' , 'Dhruv-Bhati' , 'DhruvBhati(201)' , '2017-08-16 21:04:05' ) ;
 
INSERT INTO `bciccom_db`.`3cx_users`  VALUES ('4' , 'Shari' , 'Shari' , 'Shari(103)' , '2017-08-16 21:04:09' ) ;
 
