<?php

//gmail parameters
$mailCdn = array(

    'Gmail' => [
	
		'_user_access' => [
		
			'user_name' => base64_encode('ashishg.business2sell@gmail.com')
		
		],
		'_user_pass_word_access' => [
		
			'user_pass_parser' => base64_encode( 'ashish@123' )
		
		]
	
	],
	'Yahoo' => [
	
		'_user_access' => [
		
			'user_name' => 'ashish@business2sell.com.au'
		
		],
		'_user_pass_word_access' => [
		
			'user_pass_parser' => 'ashish'
		
		]
	
	],
	'Bcic' => [
		
		'_user_access' => [
		
			'user_name' => base64_encode('test_1@bcic.com.au')
			//'user_name' => base64_encode('pankaj.business2sell@gmail.com')
		
		],
		'_user_pass_word_access' => [
		
			'user_pass_parser' => base64_encode('I]Xy^z01AEHz')
			//'user_pass_parser' => base64_encode('gupta@123')
		
		]
		
	],
	'B2s' => [
		
		'_user_access' => [
		
			'user_name' => base64_encode('pankaj.business2sell@gmail.com')
		
		],
		'_user_pass_word_access' => [
		
			'user_pass_parser' => base64_encode('gupta@123')
		
		]
		
	]

);


?>