<p>Hello $name,<br /> <br />Once again, we are here to make sure you have booked your cleaning job.<br /> <br /> <span style="color: #ffa500;"><span style="background-color: #ffffff;">&nbsp;</span><strong><span style="background-color: #ffffff;">IT IS OUR MISSION TO GET YOUR BOND BACK</span></strong></span></p>
<p>We understand that moving houses are in <strong>TOP 10 STRESS-FULL ACTIVITIES</strong> people avoid.<br /> <br /> That&rsquo;s why It is our tailormade approach to your needs that makes us stand out of the crowd and that our prices are reasonable with satisfaction guaranteed. ?</p>
<h4><span style="color: #ffa500;"><strong>Why should you choose us? </strong></span></h4>
<p><span style="color: #33ccff;"><strong>We are open 7 days a week:</strong></span><br /> Our Teams work from 7.30 am to 7.30 pm all 5 days and 7.30 am to 4.00 pm on weekends.<br /> We literally work 364 Days a year (Christmas and New Year we party)</p>
<p><span style="color: #33ccff;"><strong>FIXED PRICE QUOTES, No Surprises:</strong></span><br /> Our Quotes are 99.9% accurate but to make it 100%, You can send your property Images to the link below and we will make sure your Quote is a FIXED PRICE, no surprises.</p>
<p><span style="color: #33ccff;"><strong>Process that simply works:</strong></span><br /> We are upfront and open to make your move stress free. We give fixed Quotes; our cleaners call you a day before the job.<br /> We make sure cleaners are on time, Our Cleaners do carry a Check list for your property, and at the end we do send you an email with the copy of the check list and images of before and after of the property.</p>
<p><span style="color: #33ccff;"><strong>7 days Warranty:</strong></span><br /> We try our best to make sure all the issues have been resolved and we dont have to return, still have a 7-day warranty for your piece of mind.<br /> If your real estate can send us the exit report, we send the cleaners as soon as possible (48 hours max) to resolve any issue that may arise.</p>
<p><span style="color: #33ccff;"><strong>We deal with your Real Estate:</strong></span><br /> We will deal with your real estate and make sure that you dont have to be involved unless you are required by them.</p>
<p><span style="color: #33ccff;"><strong>We do CARE:</strong></span><br /> BCIC is a National Company and we have highly efficientadmin staff who are specially trained to look after your needs.<br /> Our cleaners know, &ldquo;Without caring there can be no quality&rdquo;</p>
<p><strong><span style="color: #33ccff;">It is your choice;</span> do you wish to save few dollars </strong><span style="color: #ff8c00;"><strong>and have stress or choose a professional company and have a </strong></span><strong>STRESS-FREE MOVE</strong><strong>. </strong><br /> <br /> <span style="color: #ff8c00;"><strong> To have a </strong></span><strong>STRESS-FREE MOVE</strong><strong>, <span style="color: #ff8c00;">please call us now on</span> $s_number&nbsp;</strong><span style="color: #ffa500;"><strong>&nbsp;or</strong></span></p>
$getlink
<p><u> </u><br /> <br /> <strong> No Body likes spam?</strong><br /> If you have already booked your job and do not wish to hear from us, we understand.<br /> please click this link below and we would only send you a Christmas card if you allow us.<br /> $spamlink<br /> <br /> Thank you again for your time, we wish you wonderful day and looking forward to hearing from you.</p>
<p><span style="color: #ffa500;"><strong>IT IS OUR MISSION TO GET YOUR BOND BACK</strong></span><br /> <br /> $quotforname&nbsp;<br /> Sales $adminname</p>